Fix long polling issue for play 2.6
Atmosphere/atmosphere-play pull request #49
Opened 2020-11-09 07:22 UTC by manipah

2020-11-09 07:25 UTC, manipah commented
@jfarcand hi this is the pr we talked about in the email, please have a look :)

2020-11-09 15:28 UTC, jfarcand requested changes

2020-11-09 15:28 UTC, jfarcand commented on module/pom.xml
> +    <version>2.4.2</version>
Do not change the version.It will be automatically bumped when the official release happens

2020-11-09 15:28 UTC, jfarcand commented on pom.xml
> +    <version>2.4.2</version>
Same here

2020-11-10 08:22 UTC, manipah commented on module/pom.xml
> +    <version>2.4.2</version>
```suggestion
    <version>2.4.1-SNAPSHOT<</version>
```

2020-11-10 08:22 UTC, manipah commented on pom.xml
> +    <version>2.4.2</version>
```suggestion
    <version>2.4.1-SNAPSHOT</version>
```

2020-11-10 08:24 UTC, manipah commented on module/pom.xml
> +    <version>2.4.1-SNAPSHOT<</version>
```suggestion
    <version>2.4.1-SNAPSHOT</version>
```

2020-11-10 14:02 UTC, jfarcand approved these changes

2020-11-10 14:02 UTC, merged